// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transformese.Data;

#nullable disable

namespace Transformese.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117125759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Transformese.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("IdCurso");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            IdCurso = 1,
                            Descricao = "Conceitos iniciais de computação",
                            Imagem = "default-course.jpg",
                            Nome = "Informática Básica",
                            UnidadeId = 1
                        },
                        new
                        {
                            IdCurso = 2,
                            Descricao = "Lógica e orientação a objetos",
                            Imagem = "default-course.jpg",
                            Nome = "Programação C#",
                            UnidadeId = 1
                        },
                        new
                        {
                            IdCurso = 3,
                            Descricao = "Ferramentas visuais e criatividade",
                            Imagem = "default-course.jpg",
                            Nome = "Design Gráfico",
                            UnidadeId = 2
                        },
                        new
                        {
                            IdCurso = 4,
                            Descricao = "Infraestrutura e comunicação",
                            Imagem = "default-course.jpg",
                            Nome = "Redes de Computadores",
                            UnidadeId = 2
                        },
                        new
                        {
                            IdCurso = 5,
                            Descricao = "Automação e análise de dados",
                            Imagem = "default-course.jpg",
                            Nome = "Excel Avançado",
                            UnidadeId = 3
                        },
                        new
                        {
                            IdCurso = 6,
                            Descricao = "HTML, CSS e JavaScript",
                            Imagem = "default-course.jpg",
                            Nome = "Desenvolvimento Web",
                            UnidadeId = 3
                        },
                        new
                        {
                            IdCurso = 7,
                            Descricao = "Modelagem e SQL",
                            Imagem = "default-course.jpg",
                            Nome = "Banco de Dados",
                            UnidadeId = 4
                        },
                        new
                        {
                            IdCurso = 8,
                            Descricao = "Edição e manipulação de imagens",
                            Imagem = "default-course.jpg",
                            Nome = "Photoshop",
                            UnidadeId = 4
                        },
                        new
                        {
                            IdCurso = 9,
                            Descricao = "Estratégias e campanhas online",
                            Imagem = "default-course.jpg",
                            Nome = "Marketing Digital",
                            UnidadeId = 5
                        },
                        new
                        {
                            IdCurso = 10,
                            Descricao = "Visualização e dashboard",
                            Imagem = "default-course.jpg",
                            Nome = "Power BI",
                            UnidadeId = 5
                        });
                });

            modelBuilder.Entity("Transformese.Domain.Entities.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoUsuario"));

                    b.Property<string>("DescricaoTipoUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("TiposUsuarios");

                    b.HasData(
                        new
                        {
                            IdTipoUsuario = 1,
                            DescricaoTipoUsuario = "Administrador"
                        },
                        new
                        {
                            IdTipoUsuario = 2,
                            DescricaoTipoUsuario = "Professor"
                        },
                        new
                        {
                            IdTipoUsuario = 3,
                            DescricaoTipoUsuario = "Aluno"
                        });
                });

            modelBuilder.Entity("Transformese.Domain.Entities.Unidade", b =>
                {
                    b.Property<int>("IdUnidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidade"));

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUnidade");

                    b.ToTable("Unidades");

                    b.HasData(
                        new
                        {
                            IdUnidade = 1,
                            Endereco = "Rua A, 100",
                            Nome = "Unidade São Miguel"
                        },
                        new
                        {
                            IdUnidade = 2,
                            Endereco = "Av B, 200",
                            Nome = "Unidade Itaquera"
                        },
                        new
                        {
                            IdUnidade = 3,
                            Endereco = "Rua C, 300",
                            Nome = "Unidade Tatuapé"
                        },
                        new
                        {
                            IdUnidade = 4,
                            Endereco = "Rua D, 400",
                            Nome = "Unidade Penha"
                        },
                        new
                        {
                            IdUnidade = 5,
                            Endereco = "Av E, 500",
                            Nome = "Unidade São Mateus"
                        });
                });

            modelBuilder.Entity("Transformese.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            DataNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Admin do Sistema",
                            Senha = "123456",
                            TipoUsuarioId = 1
                        },
                        new
                        {
                            IdUsuario = 2,
                            DataNascimento = new DateTime(1985, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carlos.prof@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Carlos Henrique",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 3,
                            DataNascimento = new DateTime(1987, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marina.prof@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Marina Lopes",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 4,
                            DataNascimento = new DateTime(1982, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joao.prof@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "João Batista",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 5,
                            DataNascimento = new DateTime(1990, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patricia.prof@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Patrícia Santos",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 6,
                            DataNascimento = new DateTime(2000, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno1@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 1",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 7,
                            DataNascimento = new DateTime(2000, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno2@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 2",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 8,
                            DataNascimento = new DateTime(2000, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno3@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 3",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 9,
                            DataNascimento = new DateTime(2000, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno4@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 4",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 10,
                            DataNascimento = new DateTime(2000, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno5@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 5",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 11,
                            DataNascimento = new DateTime(2000, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno6@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 6",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 12,
                            DataNascimento = new DateTime(2000, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno7@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 7",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 13,
                            DataNascimento = new DateTime(2000, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno8@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 8",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 14,
                            DataNascimento = new DateTime(2000, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno9@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 9",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 15,
                            DataNascimento = new DateTime(2000, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno10@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 10",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 16,
                            DataNascimento = new DateTime(2000, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno11@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 11",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 17,
                            DataNascimento = new DateTime(2000, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno12@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 12",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 18,
                            DataNascimento = new DateTime(2000, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno13@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 13",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 19,
                            DataNascimento = new DateTime(2000, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno14@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 14",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        },
                        new
                        {
                            IdUsuario = 20,
                            DataNascimento = new DateTime(2000, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aluno15@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Aluno 15",
                            Senha = "123456",
                            TipoUsuarioId = 3
                        });
                });

            modelBuilder.Entity("Transformese.Domain.Entities.Curso", b =>
                {
                    b.HasOne("Transformese.Domain.Entities.Unidade", "Unidade")
                        .WithMany("Cursos")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Transformese.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Transformese.Domain.Entities.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Transformese.Domain.Entities.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Transformese.Domain.Entities.Unidade", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
